import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { PrintReport } from "@/components/audit/print-report";
import { auditStore } from "@/lib/db/audit-store";
import { siteConfig } from "@/lib/config/site";
import { displayUrl } from "@/lib/utils/url";

/**
 * The printable report.
 *
 * A separate page rather than a print stylesheet over the interactive one,
 * because the two want genuinely different layouts: no navigation, no filter
 * controls, and every check expanded rather than hidden inside a collapsed
 * element that a printer would omit.
 *
 * "Download PDF" is the browser's own print-to-PDF. That produces a real,
 * selectable-text PDF with no extra dependency and no server-side rendering
 * service — and it works offline.
 */

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const stored = await auditStore.get(id);
  const target = stored ? displayUrl(stored.finalUrl ?? stored.url, 50) : "report";

  return {
    title: `SEO report for ${target} — printable`,
    description: `Printable SEO audit report generated by ${siteConfig.name}.`,
    robots: { index: false, follow: false, nocache: true },
  };
}

export default async function PrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  if (!/^[a-z0-9]{10,40}$/.test(id)) notFound();

  const stored = await auditStore.get(id);
  if (!stored || stored.state !== "COMPLETED" || !stored.report) notFound();

  return <PrintReport report={stored.report} shareUrl={`${siteConfig.url}/audit/${stored.id}`} />;
}
