import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * ESLint configuration (flat config).
 *
 * From Next 16 onwards, `eslint-config-next` exports flat config arrays
 * directly, so they are spread in rather than wrapped in FlatCompat.
 */
const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by `prisma generate` on every install — not our code to lint.
      "lib/db/generated/**",
      "playwright-report/**",
      "test-results/**",
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    rules: {
      // An underscore prefix is the conventional way to say "deliberately
      // unused", usually a positional parameter we have to accept.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default eslintConfig;
