import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft } from "lucide-react";

import { ReportView } from "@/components/audit/report-view";
import { AuditForm } from "@/components/audit/audit-form";
import { Alert, ButtonLink, Card, Container } from "@/components/ui";
import { auditStore } from "@/lib/db/audit-store";
import { siteConfig } from "@/lib/config/site";
import { displayUrl } from "@/lib/utils/url";

/**
 * The saved report page.
 *
 * A report lives at its own URL so it can be revisited, bookmarked and shared.
 * Ids are 120 bits of randomness, so a report cannot be found by guessing —
 * but anyone with the link can read it, which is exactly what makes sharing
 * work. The privacy policy says so plainly.
 *
 * Reports are NOT indexable: an audit of someone else's page is not our
 * content to publish, and a search engine has no business listing it.
 */

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const stored = await auditStore.get(id);

  if (!stored) {
    return { title: "Report not found", robots: { index: false, follow: false } };
  }

  const target = displayUrl(stored.finalUrl ?? stored.url, 50);

  return {
    title:
      stored.state === "COMPLETED" && stored.report
        ? `SEO report for ${target} — ${stored.report.score.total}/100`
        : `SEO report for ${target}`,
    description: `An automated on-page and technical SEO audit of ${target}, generated by ${siteConfig.name}.`,
    robots: { index: false, follow: false, nocache: true },
  };
}

export default async function AuditPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  if (!/^[a-z0-9]{10,40}$/.test(id)) notFound();

  const stored = await auditStore.get(id);
  if (!stored) notFound();

  /* -- A failed audit is still a report worth showing -------------------- */
  if (stored.state === "FAILED" || !stored.report) {
    return (
      <Container size="narrow" className="py-12 sm:py-16">
        <Link
          href="/seo-checker"
          className="inline-flex items-center gap-1.5 text-sm text-ink-600 hover:text-ink-950"
        >
          <ArrowLeft className="h-4 w-4" aria-hidden="true" />
          Back to the checker
        </Link>

        <h1 className="mt-6 text-2xl font-semibold sm:text-3xl">We could not audit this page</h1>

        <Card className="mt-6 px-5 py-5">
          <p className="text-xs font-semibold uppercase tracking-[0.14em] text-ink-500">
            URL requested
          </p>
          <p className="mt-1.5 break-words font-mono text-sm text-ink-900">{stored.url}</p>

          <Alert
            tone="warning"
            className="mt-5"
            icon={<AlertTriangle className="h-4 w-4" aria-hidden="true" />}
            title={stored.error?.message ?? "The page could not be analyzed."}
          >
            <p className="mt-1 text-[13px] leading-relaxed">
              Reference: <span className="font-mono">{stored.error?.code ?? "UNKNOWN"}</span>
            </p>
          </Alert>

          <div className="mt-5 text-sm leading-relaxed text-ink-600">
            <p className="font-medium text-ink-900">Things worth checking</p>
            <ul className="mt-2 space-y-1.5">
              <li>Open the URL in a browser and confirm it loads for you.</li>
              <li>Check the address is spelled correctly, including https://.</li>
              <li>
                Some sites block automated requests. If the page loads for you but not for us, that
                is the most likely reason.
              </li>
            </ul>
          </div>
        </Card>

        <div className="mt-8">
          <h2 className="text-[15px] font-semibold">Try another URL</h2>
          <AuditForm className="mt-3" size="md" />
        </div>
      </Container>
    );
  }

  const shareUrl = `${siteConfig.url}/audit/${stored.id}`;

  return (
    <>
      <ReportView report={stored.report} shareUrl={shareUrl} />

      <Container className="pb-12 no-print">
        <Card className="flex flex-col items-start justify-between gap-4 px-5 py-5 sm:flex-row sm:items-center">
          <div>
            <h2 className="text-[15px] font-semibold">Check another page</h2>
            <p className="mt-1 text-sm text-ink-600">
              Reports are kept for a limited time and then deleted automatically.
            </p>
          </div>
          <ButtonLink href="/seo-checker" size="md">
            Run a new audit
          </ButtonLink>
        </Card>
      </Container>
    </>
  );
}
